DECLARE
@BAIRRO VARCHAR(50),
@CIDADE VARCHAR(50),
@CONTADOROFFSET INT,
@CONTADORCLIENTE INT;
DECLARE @TABELABAIRRO TABLE(BAIRRO VARCHAR(50), CIDADE VARCHAR(50));

SET @CIDADE = 'Rio de Janeiro';
SET @CONTADOROFFSET = 0;

SELECT @CONTADORCLIENTE = COUNT(*) FROM [TABELA DE CLIENTES] 
WHERE CIDADE = @CIDADE;

WHILE @CONTADOROFFSET < @CONTADORCLIENTE
	BEGIN

	SELECT DISTINCT @BAIRRO = BAIRRO
	FROM [TABELA DE CLIENTES]
	WHERE CIDADE = @CIDADE
	ORDER BY BAIRRO
	OFFSET @CONTADOROFFSET ROWS
	FETCH NEXT 1 ROWS ONLY;

	INSERT INTO @TABELABAIRRO VALUES (@BAIRRO, @CIDADE);

	SET @CONTADOROFFSET = @CONTADOROFFSET + 1;

	END;

	SELECT * FROM @TABELABAIRRO


