SELECT * FROM CLIENTE ORDER BY 1;

CREATE OR REPLACE PROCEDURE ALTERA_SEGMERCADO
(p_ID IN CLIENTE.ID%TYPE, p_IDSEGMERCADO IN CLIENTE.SEGMERCADO_ID%TYPE)
IS
BEGIN
  UPDATE CLIENTE SET SEGMERCADO_ID = p_IDSEGMERCADO WHERE ID = p_ID; 
  COMMIT;
END;


SET SERVEROUTPUT ON;

DECLARE
v_ID CLIENTE.ID%TYPE := 111;
v_IDSEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 1;

BEGIN
    ALTERA_SEGMERCADO(v_ID, v_IDSEGMERCADO);
    
    
END;

