-- Exercicio 4
-- Incluindo uma venda com Procedures

SELECT * FROM PRODUTO_VENDA_EXERCICIO;
SELECT * FROM PRODUTO_EXERCICIO;


CREATE OR REPLACE PROCEDURE INCLUINDO_DADOS_VENDA
(p_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE, p_CODPRODUTO PRODUTO_VENDA_EXERCICIO.COD_PRODUTO%TYPE,
 p_DATE PRODUTO_VENDA_EXERCICIO.DATA%TYPE, p_QUANTIDADE PRODUTO_VENDA_EXERCICIO.QUANTIDADE%TYPE, p_PRECO PRODUTO_VENDA_EXERCICIO.PRECO%TYPE,
 p_VALORTOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE, p_PERCENTUALIMPOSTO PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE)
IS

BEGIN
    INSERT INTO PRODUTO_VENDA_EXERCICIO VALUES (p_ID, p_CODPRODUTO, p_DATE, p_QUANTIDADE, p_PRECO, p_VALORTOTAL, p_PERCENTUALIMPOSTO);
    COMMIT;
END;

EXECUTE INCLUINDO_DADOS_VENDA(1, '41232','01-01-2022', 100, 10, 1000, 10);

