-- Exercicio 3
-- Construa uma função com o nome RETORNA_CATEGORIA que, passando o código do produto, teremos o retorno da categoria.

SELECT * FROM PRODUTO_EXERCICIO;

CREATE OR REPLACE FUNCTION RETORNA_CATEGORIA
(p_COD PRODUTO_EXERCICIO.COD%TYPE)
RETURN PRODUTO_EXERCICIO.CATEGORIA%TYPE
IS
    v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE;
BEGIN
    SELECT CATEGORIA INTO v_CATEGORIA FROM PRODUTO_EXERCICIO WHERE COD = p_COD;
    
    RETURN v_CATEGORIA;
END;


SELECT RETORNA_CATEGORIA(92347) FROM PRODUTO_EXERCICIO
WHERE ROWNUM = 1;