-- Exercicio 05 
/* Crie uma procedure que, dado um identificador da venda (ID ), 
da tabela PRODUTO_VENDA_EXERCICIO, temos como retorno o valor financeiro do imposto. 
O parâmetro referente ao resultado do imposto deve ser passado para essa procedure como um parâmetro OUT. */

SELECT * FROM PRODUTO_VENDA_EXERCICIO;

SELECT ((PRECO * VALOR_TOTAL) * (PERCENTUAL_IMPOSTO / 100)) FROM PRODUTO_VENDA_EXERCICIO WHERE ID = 1;

CREATE OR REPLACE PROCEDURE CALCULA_IMPOSTO
(p_ID IN PRODUTO_VENDA_EXERCICIO.ID%TYPE, p_RESULTADO OUT PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE)
IS
BEGIN
    SELECT ((PRECO * VALOR_TOTAL) * (PERCENTUAL_IMPOSTO / 100)) INTO p_RESULTADO FROM PRODUTO_VENDA_EXERCICIO WHERE ID = p_ID;
END;



SET SERVEROUTPUT ON;

DECLARE
   v_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE := 2;
   v_RESULTADO PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
BEGIN
   CALCULA_IMPOSTO(v_ID, v_RESULTADO);
   DBMS_OUTPUT.PUT_LINE('O imposto calculado é: ' || v_RESULTADO);
END;

