-- Altere todas descrições que possuem '-' por '>'

SELECT * FROM PRODUTO_EXERCICIO;

DECLARE 
    v_COD PRODUTO_EXERCICIO.COD%type;
    v_DESCRICAO PRODUTO_EXERCICIO.DESCRICAO%type;
    
BEGIN
    v_COD := 3223;
    UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO, '-', '>') WHERE COD = v_COD;
    
    v_COD := 67120;
    UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO, '-', '>') WHERE COD = v_COD;
    
    v_COD := 41232;
    UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO, '-', '>') WHERE COD = v_COD;
    
    COMMIT;
END;