SELECT * FROM aluno;
SELECT * FROM CURSO;

INSERT INTO ALUNO (NOME_ALUNO, IDADE)
VALUES
('Pedro', 20);


INSERT INTO CURSO(NOME_CURSO)
VALUES
('HTML'),
('Java'),
('JavaScript'),
('SQL'),
('Dart')

CREATE TABLE ALUNO(
ID_ALUNO SERIAL PRIMARY KEY,
NOME_ALUNO VARCHAR(100),
IDADE INT);

CREATE TABLE CURSO(
ID_CURSO SERIAL PRIMARY KEY,
NOME_CURSO VARCHAR(100));

CREATE TABLE CURSO_ALUNO(
ID_ALUNO INTEGER,
ID_CURSO INTEGER,
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID_ALUNO),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO));  


SELECT * FROM CURSO_ALUNO

INSERT INTO CURSO_ALUNO
VALUES
(6)


SELECT A.NOME_ALUNO "NOME ALUNO", B.ID_CURSO, B.NOME_CURSO FROM ALUNO A
LEFT JOIN CURSO_ALUNO C
ON A.ID_ALUNO = C.ID_ALUNO
LEFT JOIN CURSO B
ON B.ID_CURSO = C.ID_CURSO

SELECT A.ID_ALUNO, A.NOME_ALUNO, C.ID_CURSO, C.NOME_CURSO
FROM ALUNO A
JOIN CURSO_ALUNO CA ON A.ID_ALUNO = CA.ID_ALUNO
JOIN CURSO C ON CA.ID_CURSO = C.ID_CURSO;

SELECT A.*, B.* FROM ALUNO A
RIGHT JOIN CURSO B
ON A.ID_ALUNO = B.ID_CURSO

SELECT * FROM CURSO_ALUNO

DELETE FROM ALUNO 
WHERE ID_ALUNO = 3
