CREATE TABLE ALUNOS (
	ID SERIAL,
	NOME VARCHAR(255),
	CPF CHAR(11),
	OBSERVACAO TEXT,
	IDADE INT,
	DINHEIRO NUMERIC(10,2),
	ALTURA REAL,
	ATIVO BOOLEAN,
	DATA_NASCIMENTO DATE,
	HORA_AULA TIME,
	MATRICULA_DATA TIMESTAMP
);

SELECT * FROM ALUNOS