SELECT EXTRACT(MONTH FROM DATA_NASCIMENTO) FROM ALUNO
WHERE EXTRACT(MONTH FROM DATA_NASCIMENTO) = 11


CREATE TABLE CURSO(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100)
)

INSERT INTO CURSO(NOME)
VALUES
('A'),
('B'),
('C'),
('D');

CREATE TABLE ALUNO(
ID_ALUNO SERIAL PRIMARY KEY,
NOME_ALUNO VARCHAR(100),
IDADE INT NOT NULL,
ID_CURSO INT NOT NULL)

ALTER TABLE ALUNO
ADD CONSTRAINT FK_CURSO_ALUNO FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID)

INSERT INTO ALUNO(nome_aluno, IDADE, ID_CURSO)
VALUES
('C', 18, 2)

SELECT * FROM ALUNO

SELECT NOME_ALUNO "Nome do Aluno", NOME "Nome do Curso" FROM ALUNO A
INNER JOIN 
CURSO B
ON A.ID_CURSO = B.ID
