-- Desafio
-- Criei um procedure para atualizar o CNPJ e CATEGORIA, pois eles estavam sem formatação.
SELECT * FROM CLIENTE ORDER BY 1;

CREATE OR REPLACE PROCEDURE ATUALIZA_CLIENTE
IS
v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
v_CONTACLIENTE INTEGER;
v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE;
v_CNPJ CLIENTE.CNPJ%TYPE;
v_CNPJ_SAIDA CLIENTE.CNPJ%TYPE;
BEGIN
    SELECT COUNT(*) INTO v_CONTACLIENTE FROM CLIENTE; 
    FOR v_ID IN 1..v_CONTACLIENTE LOOP
        SELECT FATURAMENTO_PREVISTO INTO v_FATURAMENTO FROM CLIENTE WHERE ID = v_ID;
        SELECT CATEGORIA_CLIENTE(v_FATURAMENTO) INTO v_CATEGORIA FROM CLIENTE WHERE ID = v_ID;
        SELECT REGEXP_REPLACE(CNPJ, '[^0-9]', '') INTO v_CNPJ FROM CLIENTE WHERE ID = v_ID;
        FORMATACAO_CNPJ(v_CNPJ, v_CNPJ_SAIDA);
        
        UPDATE CLIENTE SET CATEGORIA = v_CATEGORIA WHERE ID = v_ID;
        UPDATE CLIENTE SET CNPJ = v_CNPJ_SAIDA WHERE ID = v_ID;
        
        COMMIT;
    END LOOP;
END;


EXECUTE ATUALIZA_CLIENTE();
