-- Criar uma função para calcular imposto
-- Sucos = 10%
-- Águas = 20%
-- Mate = 15%

SELECT A.*, b.* FROM PRODUTO_EXERCICIO A
INNER JOIN PRODUTO_VENDA_EXERCICIO B
ON A.COD = b.cod_produto;

SELECT * FROM PRODUTO_EXERCICIO;

SELECT RETORNA_IMPOSTO('3223') FROM PRODUTO_EXERCICIO;

CREATE OR REPLACE FUNCTION RETORNA_IMPOSTO
(p_COD PRODUTO_EXERCICIO.COD%TYPE)
RETURN PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE
IS
v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE;
v_PERCENTUAL PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE := 0;
BEGIN
    -- Usando uma funçao que já criamos
    v_CATEGORIA := RETORNA_CATEGORIA(p_COD);

    IF v_CATEGORIA LIKE('%Suco%') THEN v_PERCENTUAL := 0.10;
    ELSIF v_CATEGORIA = 'Águas' THEN v_PERCENTUAL := 0.20;
    ELSIF v_CATEGORIA = 'Mate' THEN v_PERCENTUAL := 0.15;
    END IF;

    RETURN v_PERCENTUAL;
    
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
END;