-- Desafio
/*  
- Faça uma procedure que percorra, de forma sequencial, o valor do identificador da venda (ID) 
e atualize, na tabela PRODUTO_VENDA_EXERCICIO, as colunas VALOR_TOTAL e PERCENTUAL_IMPOSTO
      
- Note que o campo VALOR_TOTAL, que deveria ser a QUANTIDADE x PRECO, 
não está calculado corretamente, bem como o PERCENTUAL_IMPOSTO, que está vazio. 
Relembrando que o PERCENTUAL_IMPOSTO é obtido da função RETORNA_IMPOSTO.

- Crie uma função para retornar o cálculo QUANTIDADE * PRECO
*/


INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (3, '41232',TO_DATE('01/02/2022','DD/MM/YYYY'), 250, 20, 0, 0);
INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (4, '32223',TO_DATE('03/02/2022','DD/MM/YYYY'), 200, 16, 0, 0);
INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (5, '92347',TO_DATE('05/02/2022','DD/MM/YYYY'), 200, 16, 0, 0);
INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (6, '41232',TO_DATE('02/03/2022','DD/MM/YYYY'), 210, 19, 0, 0);
INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (7, '33854',TO_DATE('05/03/2022','DD/MM/YYYY'), 180, 21, 0, 0);
INSERT INTO PRODUTO_VENDA_EXERCICIO
VALUES (8, '92347',TO_DATE('09/03/2022','DD/MM/YYYY'), 170, 20, 0, 0);

CREATE OR REPLACE PROCEDURE ATUALIZA_VALOR
IS
p_ID PRODUTO_VENDA_EXERCICIO.ID%TYPE := 1;
p_COD PRODUTO_EXERCICIO.COD%TYPE;
p_IMPOSTO PRODUTO_VENDA_EXERCICIO.PERCENTUAL_IMPOSTO%TYPE;
p_CONTAID PRODUTO_VENDA_EXERCICIO.ID%TYPE;
p_VALOR_TOTAL PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
BEGIN

    SELECT COUNT(*) INTO p_CONTAID FROM PRODUTO_VENDA_EXERCICIO;
    LOOP
        SELECT COD_PRODUTO INTO p_COD FROM PRODUTO_VENDA_EXERCICIO WHERE ID = p_ID;
        SELECT RETORNA_IMPOSTO(p_COD) INTO p_IMPOSTO FROM PRODUTO_VENDA_EXERCICIO WHERE ID = p_ID;
        UPDATE PRODUTO_VENDA_EXERCICIO SET PERCENTUAL_IMPOSTO = p_IMPOSTO WHERE ID = p_ID;
        
        SELECT RETORNA_VALORTOTAL(QUANTIDADE, PRECO) INTO p_VALOR_TOTAL FROM PRODUTO_VENDA_EXERCICIO WHERE ID = p_ID;
        UPDATE PRODUTO_VENDA_EXERCICIO SET VALOR_TOTAL = p_VALOR_TOTAL WHERE ID = p_ID;
        
        p_ID := p_ID + 1;
        EXIT WHEN p_ID > p_CONTAID;
    END LOOP;
END;

-- Executa a PROCEDURE
EXECUTE ATUALIZA_VALOR();

-- Criando a função
CREATE OR REPLACE FUNCTION RETORNA_VALORTOTAL (
    p_QUANTIDADE PRODUTO_VENDA_EXERCICIO.QUANTIDADE%TYPE,
    p_PRECO PRODUTO_VENDA_EXERCICIO.PRECO%TYPE)
RETURN PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE
IS
    v_RESULTADO PRODUTO_VENDA_EXERCICIO.VALOR_TOTAL%TYPE;
BEGIN
    v_RESULTADO := (p_Quantidade * p_PRECO);
    
    RETURN v_RESULTADO;
END;

SELECT RETORNA_VALORTOTAL(QUANTIDADE, PRECO) FROM PRODUTO_VENDA_EXERCICIO WHERE ID = 1 ORDER BY 1;