-- Alterando a Procedure para usar a função de CATEGORIA

CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
(p_ID CLIENTE.ID%TYPE, p_RAZAO CLIENTE.RAZAO_SOCIAL%TYPE, p_CNPJ CLIENTE.CNPJ%TYPE, p_SEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE,
 p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS
v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    
    v_CATEGORIA := CLASSIFICANDO_CATEGORIA(p_FATURAMENTO);
    
    INSERT INTO CLIENTE VALUES(p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
    COMMIT;
END;
