-- Usando Bind com DataType

SET AUTOPRINT ON;

VARIABLE B_LN varchar2(50)
VARIABLE B_SAL FLOAT

DECLARE 
    V_EI EMPLOYEES.EMPLOYEE_ID%TYPE := 100;
    
    BEGIN
    SELECT LAST_NAME, SALARY
    INTO :B_LN, :B_SAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = V_EI;
    END;
/

print B_LN B_SAL;
