SET SERVEROUT ON;

-- DATATYPE "%" PARA PASSAR O VALORES DA TABELA EM UMA VARIAVEL
DECLARE 
V_EI EMPLOYEES.EMPLOYEE_ID%TYPE NOT NULL := 5;
V_LN EMPLOYEES.LAST_NAME%TYPE;
C_TAX CONSTANT NUMBER(5) := 4;
V_HIRE_DATE DATE := SYSDATE;
V_RETIRED_DATE V_HIRE_DATE%TYPE := SYSDATE;
V_TAX C_TAX%TYPE;


BEGIN



DBMS_OUTPUT.PUT_LINE('Teste');

END;


