-- Desafio Geral 02
-- Listas o codigo e nome do produto com valor total (quantidade * preço) por determinado mês
-- Usando T-SQL
-- Usando tabela temporaria

DECLARE
@CODIGO VARCHAR(7),
@NOMEPRODUTO VARCHAR(100),
@NUMPRODUTO INT,
@VALOR VARCHAR(100),
@I INT,
@ANO VARCHAR(4),
@MES VARCHAR(2);
-- TABELA TEMPORARIA
DECLARE @TABELAFINAL TABLE(CODIGO VARCHAR(7), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL VARCHAR(100));

SET @I = 1;
SET @ANO = '2015';
SET @MES = '1';


SELECT @NUMPRODUTO = COUNT(*) FROM [TABELA DE PRODUTOS]

WHILE @I <= @NUMPRODUTO
	BEGIN
	SELECT @CODIGO = A.[CODIGO DO PRODUTO], @NOMEPRODUTO = A.[NOME DO PRODUTO] 
	FROM (SELECT ROW_NUMBER() OVER (ORDER BY [CODIGO DO PRODUTO]) 'RowNum', *
			FROM [TABELA DE PRODUTOS]) A
	WHERE RowNum = @I;

	SELECT @VALOR = SUM(A.QUANTIDADE * A.PREÇO)
	FROM [ITENS NOTAS FISCAIS] A
	INNER JOIN [TABELA DE PRODUTOS] B
	ON A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO]
	INNER JOIN [NOTAS FISCAIS] C
	ON A.NUMERO = C.NUMERO
	WHERE A.[CODIGO DO PRODUTO] = @CODIGO
	AND YEAR(C.DATA) = @ANO AND MONTH(C.DATA) = @MES

	PRINT @CODIGO + ' | ' + @NOMEPRODUTO + ' | ' + TRIM(STR(@VALOR, 15,2)) + ' | ' + @ANO + ' | ' + @MES;

	INSERT INTO @TABELAFINAL
	VALUES (@CODIGO, @NOMEPRODUTO, @MES, @ANO, @VALOR);

	SET @I = @I + 1;

	END;

	SELECT * FROM @TABELAFINAL


	