-- SINONIMOS, funciona como apelido, um nome fantasia que podemos atrubir ao componente
-- Podemos dar palavra mais amigáveis, a uma tabela, um procuderes ou funciton

-- Sintaxe
CREATE PUBLIC SYNONYM INCLUIR_CLIENTE FOR USER_DEV.INCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM ATUALIZAR_CLI_SEG_MERCADO FOR USER_DEV.ATUALIZAR_CLI_SEG_MERCADO;
CREATE PUBLIC SYNONYM ATUALIZAR_FATURAMENTO_PREVISTO FOR USER_DEV.ATUALIZAR_FATURAMENTO_PREVISTO;
CREATE PUBLIC SYNONYM EXCLUIR_CLIENTE FOR USER_DEV.EXCLUIR_CLIENTE;
CREATE PUBLIC SYNONYM CLIENTE FOR USER_DEV.CLIENTE;

CREATE PUBLIC SYNONYM INCLUINDO_PRODUTO FOR USER_DEV.INCLUINDO_PRODUTO;
CREATE PUBLIC SYNONYM INCLUINDO_DADOS_VENDAS FOR USER_DEV.INCLUINDO_DADOS_VENDAS;
CREATE PUBLIC SYNONYM PRODUTO_EXERCICIO FOR USER_DEV.PRODUTO_EXERCICIO;
CREATE PUBLIC SYNONYM PRODUTO_VENDA_EXERCICIO FOR USER_DEV.PRODUTO_VENDA_EXERCICIO;
