/* Subquery */
/* Deixando de usar HAVING para usar subquery */

SELECT * FROM (
				SELECT A.CODIGO_DO_PRODUTO, B.NOME_DO_PRODUTO, SUM(A.QUANTIDADE) 'QUANTIDADE'
				FROM ITENS_NOTAS_FISCAIS A
				INNER JOIN TABELA_DE_PRODUTOS B
				ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
				GROUP BY A.CODIGO_DO_PRODUTO, B.NOME_DO_PRODUTO) QUANTIDADE_TOTAL
WHERE QUANTIDADE_TOTAL.QUANTIDADE > 394000
ORDER BY QUANTIDADE_TOTAL.QUANTIDADE DESC