-- Desafio 01 
-- Criar uma consulta para saber por cada TAMANHO a quantidade vendidas pelo ano de 2015)
-- Criar uma nova coluna com Percentual sabendo que Percentual = (QUANTIDADE VENDIDA POR ANO / QUANTIDADE TOTAL DO ANO) * 100
-- Após finalizar, simplifique a consulta.


USE SUCOS_VENDAS

SELECT * FROM TABELA_DE_PRODUTOS
SELECT * FROM ITENS_NOTAS_FISCAIS
SELECT * FROM NOTAS_FISCAIS

SELECT DISTINCT A.TAMANHO, YEAR(C.DATA_VENDA) 'Ano', SUM(B.QUANTIDADE) 'Quantidade Anual'
FROM TABELA_DE_PRODUTOS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS C
ON B.NUMERO = C.NUMERO
WHERE YEAR(C.DATA_VENDA) = '2015'
GROUP BY A.TAMANHO, YEAR(C.DATA_VENDA)
ORDER BY 'Quantidade Anual' DESC

SELECT YEAR(B.DATA_VENDA) 'Ano' , SUM(A.QUANTIDADE) 'Venda_Total_Ano'FROM ITENS_NOTAS_FISCAIS A
INNER JOIN NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO
WHERE YEAR(B.DATA_VENDA) = 2015
group by YEAR(B.DATA_VENDA)

SELECT VS.TAMANHO, VS.Ano, VS.[Quantidade Anual],
	   CONCAT (ROUND(SUM((CONVERT(FLOAT, VS.[Quantidade Anual]) / CONVERT(FLOAT, VA.Venda_Total_Ano)) * 100),2), '%') 'Percentual' 
	   
	   FROM
				(SELECT DISTINCT A.TAMANHO, YEAR(C.DATA_VENDA) 'Ano', SUM(B.QUANTIDADE) 'Quantidade Anual'
				FROM TABELA_DE_PRODUTOS A
				INNER JOIN ITENS_NOTAS_FISCAIS B
				ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
				INNER JOIN NOTAS_FISCAIS C
				ON B.NUMERO = C.NUMERO
				WHERE YEAR(C.DATA_VENDA) = '2015'
				GROUP BY A.TAMANHO, YEAR(C.DATA_VENDA)
				) VS
INNER JOIN 
				(SELECT YEAR(B.DATA_VENDA) 'Ano' , SUM(A.QUANTIDADE) 'Venda_Total_Ano' FROM ITENS_NOTAS_FISCAIS A
				INNER JOIN NOTAS_FISCAIS B
				ON A.NUMERO = B.NUMERO
				WHERE YEAR(B.DATA_VENDA) = 2015
				group by YEAR(B.DATA_VENDA)
				) VA
ON VS.Ano = VA.Ano
GROUP BY VS.TAMANHO, VS.Ano, VS.[Quantidade Anual], VA.Venda_Total_Ano
ORDER BY VS.[Quantidade Anual] DESC

-- Criação de View para facilitar a consulta
CREATE VIEW VS AS
SELECT DISTINCT A.TAMANHO, YEAR(C.DATA_VENDA) 'Ano', SUM(B.QUANTIDADE) 'Quantidade Anual'
				FROM TABELA_DE_PRODUTOS A
				INNER JOIN ITENS_NOTAS_FISCAIS B
				ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
				INNER JOIN NOTAS_FISCAIS C
				ON B.NUMERO = C.NUMERO
				WHERE YEAR(C.DATA_VENDA) = '2015'
				GROUP BY A.TAMANHO, YEAR(C.DATA_VENDA)

SELECT * FROM VS

CREATE VIEW VA AS
SELECT YEAR(B.DATA_VENDA) 'Ano' , SUM(A.QUANTIDADE) 'Venda_Total_Ano' FROM ITENS_NOTAS_FISCAIS A
				INNER JOIN NOTAS_FISCAIS B
				ON A.NUMERO = B.NUMERO
				WHERE YEAR(B.DATA_VENDA) = 2015
				group by YEAR(B.DATA_VENDA)

SELECT * FROM VA

SELECT DISTINCT A.TAMANHO, A.ANO, A.[Quantidade Anual],
	   (ROUND((CONVERT(FLOAT, A.[Quantidade Anual]) / CONVERT(FLOAT, B.Venda_Total_Ano) * 100),2)) 'Percentual'
FROM VS A		
INNER JOIN VA B
ON A.Ano = B.Ano
INNER JOIN TABELA_DE_PRODUTOS C
ON A.TAMANHO = C.TAMANHO
ORDER BY  'Percentual' DESC