SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

--1
SELECT MANAGER_ID, JOB_ID, SUM(SALARY) "SALARY"
FROM EMPLOYEES 
WHERE MANAGER_ID < 120
GROUP BY ROLLUP (MANAGER_ID, JOB_ID);

--2 
SELECT MANAGER_ID, SUM(SALARY), GROUPING(MANAGER_ID), GROUPING(JOB_ID)
FROM EMPLOYEES
WHERE MANAGER_ID < 120
GROUP BY ROLLUP (MANAGER_ID, JOB_ID);

--3

SELECT A.MANAGER_ID, A.JOB_ID, SUM(A.SALARY) 
FROM EMPLOYEES A
WHERE A.MANAGER_ID < 120
GROUP BY cube (A.MANAGER_ID, A.JOB_ID)
ORDER BY 1;

SELECT A.MANAGER_ID, SUM(A.SALARY) 
FROM EMPLOYEES A
WHERE A.MANAGER_ID < 120
GROUP BY A.MANAGER_ID
ORDER BY 1;

SELECT A.JOB_ID, SUM(A.SALARY) 
FROM EMPLOYEES A
WHERE A.MANAGER_ID < 120
GROUP BY A.JOB_ID
ORDER BY 1;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) 
FROM EMPLOYEES
GROUP BY JOB_ID, DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT last_name 
     FROM EMPLOYEES
     WHERE LAST_NAME NOT IN('Lorentz')
    START WITH LAST_NAME = 'Lorentz'
    CONNECT BY PRIOR manager_id = employee_id;