-- Convertendo
SELECT CONVERT(varchar(25), GETDATE(), 121)

SELECT DATA_DE_NASCIMENTO, CONVERT(varchar(25), DATA_DE_NASCIMENTO, 106)
FROM TABELA_DE_CLIENTES

SELECT NOME_DO_PRODUTO, CONCAT('O PREÇO DE LISTA É: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) FROM TABELA_DE_PRODUTOS

SELECT CONCAT('O Cliente ' + A.NOME + ' comprou R$ ' + TRIM(STR(SUM(C.QUANTIDADE * C.PRECO) ,10,2)) + ' no ano de ' , YEAR(B.DATA_VENDA) )
FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
INNER JOIN ITENS_NOTAS_FISCAIS C
ON B.NUMERO = C.NUMERO
WHERE YEAR(B.DATA_VENDA) = '2016'
GROUP BY A.NOME, B.DATA_VENDA

SELECT 'O cliente ' + TC.NOME + ' comprou R$ ' + 
TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO) ,10,2)) + ' no ano de ' + DATENAME(YEAR, NF.DATA_VENDA)
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, NF.DATA_VENDA;