-- Configuração de Users

-- ALTERAR SESSÃO 
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- CRIANDO USUARIO
CREATE USER cursoplsql IDENTIFIED BY jooji123 DEFAULT TABLESPACE USERS;

-- DANDO PRIVILÉGIOS AO USUARIO, NESSE CASO INSERINDO PERMISSÃO TOTAL AO USUARIO
GRANT connect, resource TO cursoplsql;