-- While

DECLARE 
   v_SEGMERCADO CLIENTE.SEGMERCADO_ID%type := 3;
     v_ID CLIENTE.ID%type :=1;
     v_NUMCLI INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_NUMCLI FROM CLIENTE;
  WHILE v_ID <= v_NUMCLI LOOP
    ALTERA_SEGMERCADO (v_ID,v_SEGMERCADO);
            v_ID := v_ID + 1;
  END LOOP;
END;

SELECT * FROM CLIENTE;
