-- Procedures para exibir valores
SELECT * FROM SEGMERCADO;

SET SERVEROUTPUT ON;

EXECUTE EXIBIR_MERCADO(2);

CREATE OR REPLACE PROCEDURE EXIBIR_MERCADO
(p_ID SEGMERCADO.ID%TYPE)
IS
p_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN 
    SELECT DESCRICAO INTO p_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
    
    DBMS_OUTPUT.put_line('O Segmento é: ' || p_DESCRICAO);
END;