--  inclua o dia e o número de notas em uma tabela.

IF OBJECT_ID('TABELA_DATA', 'U') IS NOT NULL DROP TABLE TABELA_DATA;
CREATE TABLE TABELA_DATA (
DIA DATE,
NUMNOTAS INT
);

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATAINICIAL;

	INSERT INTO TABELA_DATA VALUES (@DATAINICIAL, @NUMNOTAS);

	SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL);
END

SELECT * FROM TABELA_DATA