-- Operador While
/* Usamos para que uma condição se repita quanta vezes for necessário,
até satisfazer uma condição */

DECLARE
@LIMITE_MINIMO INT,
@LIMITE_MAXIMO INT,
@NUM_LINHAS_MAX INT,
@NUM_LINHAS_ESCRITAS INT;

SET @LIMITE_MINIMO = 1;
SET @LIMITE_MAXIMO = 30;
SET @NUM_LINHAS_MAX = 50;
SET @NUM_LINHAS_ESCRITAS = 0;

PRINT 'ENTREI NO LOOP'
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
	BEGIN
		PRINT @LIMITE_MINIMO;
		SET @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_ESCRITAS + 1;
		IF @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_MAX
			BEGIN
				PRINT 'SAINDO DO LOOP POR CAUSA DO BREAK';
				BREAK;
			END;
		SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
	END;
PRINT 'SAI DO LOOP'