/* Usando cláusula */
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA' OR SABOR = 'LARANJA' OR SABOR = 'MELANCIA'

/* Substituir 'OR' para 'IN' */
SELECT * FROM TABELA_DE_PRODUTOS 
WHERE SABOR IN ('MANGA', 'LARANJA') 
AND TAMANHO = '1 Litro'

/* Utilizando IN com BETWEEN */
SELECT * FROM TABELA_DE_CLIENTES 
WHERE CIDADE IN ('SAO PAULO', 'RIO DE JANEIRO') 
AND (IDADE BETWEEN 20 AND 25)