-- Auto Increment no SQL Server
-- O Auto Increment é criado na criação da tabela

DROP TABLE TAB_IDENTITY;

CREATE TABLE TAB_IDENTITY (
ID INT IDENTITY(1, 1) NOT NULL,
DESCRITOR VARCHAR(20) 
);

INSERT INTO TAB_IDENTITY VALUES ('CLIENTE X');
INSERT INTO TAB_IDENTITY VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY VALUES ('CLIENTE Z');
INSERT INTO TAB_IDENTITY VALUES ('CLIENTE W');
INSERT INTO TAB_IDENTITY VALUES ('CLIENTE C');

SELECT * FROM TAB_IDENTITY;

-- Caso for deletado um ID, ele continuará fazendo o Auto Incremento, e não preencherá o ID deletado

DELETE FROM TAB_IDENTITY WHERE ID = 6;



