/* Inserindo em massa com Select */
/* Para inserir precisamos ter o mesmo tipo de coluna nas 2 tabelas*/

-- Exemplo 1
INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA 
FROM sucos_frutas.dbo.TABELA_DE_PRODUTOS

-- Exemplo 2
INSERT INTO CLIENTES (CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, GENERO,
					  LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
SELECT CPF, NOME, ENDERECO_1, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO,
		LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA
FROM sucos_frutas.DBO.TABELA_DE_CLIENTES
WHERE CPF NOT IN('1471156710', '19290992743', '2600586709')

