/* Classificação de Produtos com CASE */
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE
	WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' END) 'CLASSIFICACAO'
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
ORDER BY PRECO_DE_LISTA

/* Classificação com GROUP BY */
SELECT
(CASE
	WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' END) 'CLASSIFICACAO', COUNT(*) AS 'NUMERO DE PRODUTOS'
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
GROUP BY (CASE
	WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' END)
	ORDER BY 'NUMERO DE PRODUTOS'

/* Exemplo simples de CASE */
SELECT NOME, LIMITE_DE_CREDITO,
(CASE
	WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTES GRANDE'
	WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'CLIENTES MEDIOS'
	ELSE 'CLIENTES PEQUENOS' END) 'CLASSIFICACAO'
FROM TABELA_DE_CLIENTES




