/* Subquery com IN */
/* A Coluna que você quer consultar deve ser a mesma da coluna do subquery*/
/* Dentro da subquery não poderá ter a Ordenação (ORDER BY) */

SELECT * FROM TABELA_DE_CLIENTES 
WHERE BAIRRO IN(SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES)


/* Exemplo 2 */
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO IN (
SELECT A.CODIGO_DO_PRODUTO
FROM ITENS_NOTAS_FISCAIS  A
INNER JOIN TABELA_DE_PRODUTOS B 
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
GROUP BY A.CODIGO_DO_PRODUTO
HAVING SUM(A.QUANTIDADE) > 394000 
)