/* Criação da VIEW (Facilitar a consulta com a Subquery) */

/* Criando a VIEW */
CREATE VIEW MEDIA_EMBALAGENS AS 
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) 'PRECO MEDIO'
FROM TABELA_DE_PRODUTOS 
GROUP BY EMBALAGEM;

/* Chamando a VIEW */
SELECT * FROM MEDIA_EMBALAGENS


/* Usando VIEW com condição */
SELECT EMBALAGEM, [PRECO MEDIO]
FROM MEDIA_EMBALAGENS
WHERE [PRECO MEDIO] <= 10

/* Criando View com Inner Join */
CREATE VIEW QUANTIDADE_TOTAL AS
SELECT A.CODIGO_DO_PRODUTO, B.NOME_DO_PRODUTO, SUM(A.QUANTIDADE) 'QUANTIDADE SOMADO'
FROM ITENS_NOTAS_FISCAIS A
INNER JOIN TABELA_DE_PRODUTOS B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
GROUP BY A.CODIGO_DO_PRODUTO, B.NOME_DO_PRODUTO

/* Usando a VIEW com condição */
SELECT * FROM QUANTIDADE_TOTAL
WHERE [QUANTIDADE SOMADO] > 394000
ORDER BY [QUANTIDADE SOMADO] DESC;

