-- Exercicio 2
/* Problema 1: NA TABELA DE CLIENTES, TEMOS O LIMITE_DE_COMPRA PRECISAMOS VERIFICAR 
POR MES, SE ELE PASSOU ESSE LIMITE_DE_COMPRA, E CLASSIFICAR COM 2 CONDIÇÕES: "ULTRAPASSOU" OU "NO_LIMITE" */
/* Problema 2: Complemente este relatório, listando somente os que tiveram vendas inválidas e calculando a 
diferença entre o limite de venda máximo e o realizado, em percentuais. Dica: (1 - (VOLUME_DE_COMPRA/QUANTIDADE_VENDAS)) * 100*/

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

-- Resolução Problema 1
SELECT A.CPF, A.NOME, A.VOLUME_DE_COMPRA, TO_CHAR(B.DATA_VENDA, 'MM-YYYY') "MES_ANO" , SUM(C.QUANTIDADE) "QUANTIDADE TOTAL",
(CASE
    WHEN A.VOLUME_DE_COMPRA >= SUM(C.QUANTIDADE) THEN 'VENDAS VALIDAS'
    ELSE 'VENDAS INVALIDAS'
END) "CONDICAO"
FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
INNER JOIN ITENS_NOTAS_FISCAIS C
ON B.NUMERO = C.NUMERO
WHERE TO_CHAR(B.DATA_VENDA, 'MM-YYYY') = '02-2015'
GROUP BY A.CPF, A.NOME, A.VOLUME_DE_COMPRA, TO_CHAR(B.DATA_VENDA, 'MM-YYYY')
ORDER BY 1;

-- Resolução Problema 2
CREATE VIEW LIMITE AS
SELECT A.CPF, A.NOME, A.VOLUME_DE_COMPRA, TO_CHAR(B.DATA_VENDA, 'MM-YYYY') "MES_ANO" , SUM(C.QUANTIDADE) "QUANTIDADE_TOTAL",
(CASE
    WHEN A.VOLUME_DE_COMPRA >= SUM(C.QUANTIDADE) THEN 'VENDAS VALIDAS'
    ELSE 'VENDAS INVALIDAS'
END) "CONDICAO"
FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
INNER JOIN ITENS_NOTAS_FISCAIS C
ON B.NUMERO = C.NUMERO
WHERE TO_CHAR(B.DATA_VENDA, 'MM-YYYY') = '02-2015'
GROUP BY A.CPF, A.NOME, A.VOLUME_DE_COMPRA, TO_CHAR(B.DATA_VENDA, 'MM-YYYY')
HAVING (CASE
    WHEN A.VOLUME_DE_COMPRA >= SUM(C.QUANTIDADE) THEN 'VENDAS VALIDAS'
    ELSE 'VENDAS INVALIDAS'
END) = 'VENDAS INVALIDAS'
ORDER BY 1;

SELECT CPF, NOME, VOLUME_DE_COMPRA, MES_ANO, QUANTIDADE_TOTAL, ROUND((1 - (VOLUME_DE_COMPRA/QUANTIDADE_TOTAL)) * 100,2) || '%' "PERCENTUAL" 
FROM LIMITE;


