-- Exercício 4
/* Ranking das vendas de produtos por embalagem, dentro de um ano específico (2016);
   Coluna de percentual de distribuição de cada sabor em relação às vendas totais */
   
SELECT A.TAMANHO, EXTRACT(YEAR FROM C.DATA_VENDA) "ANO", SUM(B.QUANTIDADE) "TOTAL", ROUND((SUM(B.QUANTIDADE) / X.TOTAL) * 100,2) || '%' "PERCENTUAL"
FROM TABELA_DE_PRODUTOS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS C
ON C.NUMERO = B.NUMERO
CROSS JOIN 
            (SELECT SUM(B.QUANTIDADE) "TOTAL"
            FROM TABELA_DE_PRODUTOS A
            INNER JOIN ITENS_NOTAS_FISCAIS B
            ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
            INNER JOIN NOTAS_FISCAIS C
            ON C.NUMERO = B.NUMERO
            WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016
            ) "X"
WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016
GROUP BY A.TAMANHO, EXTRACT(YEAR FROM C.DATA_VENDA), X.TOTAL
ORDER BY 3 DESC;

