-- Queremos construir um SQL cujo resultado seja, para cada cliente:
-- O cliente NOME DO CLIENTE comprou QUANTIDADE no ano de ANO

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM ITENS_NOTAS_FISCAIS;
SELECT * FROM NOTAS_FISCAIS;

SELECT 'O CLIENTE ' || A.NOME || ' COMPROU ' || SUM(B.QUANTIDADE) || ' NO ANO DE ' || EXTRACT(YEAR FROM C.DATA_VENDA) "TEXTO" FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS C
ON A.CPF = C.CPF
INNER JOIN ITENS_NOTAS_FISCAIS B
ON B.NUMERO = C.NUMERO
WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016
GROUP BY "NOME", EXTRACT(YEAR FROM C.DATA_VENDA);