-- Exercicio 3
/* Ranking das vendas de produtos por sabor, dentro de um ano específico;
   Coluna de percentual de distribuição de cada sabor em relação às vendas totais */

-- Criando a consulta para saber a quantidade de cada sabor
SELECT A.SABOR, SUM(B.QUANTIDADE) "TOTAL" FROM TABELA_DE_PRODUTOS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS C
ON C.NUMERO = B.NUMERO
WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016
GROUP BY A.SABOR
ORDER BY "TOTAL" DESC;

-- Fazendo uma subquery para ver o percentual de cada sabor
SELECT A.SABOR, EXTRACT(YEAR FROM C.DATA_VENDA) "ANO", SUM(B.QUANTIDADE) "TOTAL", ROUND((SUM(B.QUANTIDADE) / TOTAL_SABOR) * 100,2) || '%' "PERCENTUAL" FROM TABELA_DE_PRODUTOS A
INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS C
ON C.NUMERO = B.NUMERO
CROSS JOIN
            (SELECT SUM(B.QUANTIDADE) AS TOTAL_SABOR FROM TABELA_DE_PRODUTOS A
            INNER JOIN ITENS_NOTAS_FISCAIS B
            ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
            INNER JOIN NOTAS_FISCAIS C
            ON C.NUMERO = B.NUMERO
            WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016 ) "C1"
WHERE EXTRACT(YEAR FROM C.DATA_VENDA) = 2016
GROUP BY A.SABOR, TOTAL_SABOR, EXTRACT(YEAR FROM C.DATA_VENDA)
ORDER BY 3 DESC;






