-- Functions
-- Criando uma função para retornar a descricao do segmento

SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION obter_descricao_segmercado
(p_ID IN SEGMERCADO.ID%TYPE)
RETURN SEGMERCADO.DESCRICAO%TYPE
IS
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
    
    RETURN v_DESCRICAO;
    
    COMMIT;
END;

-- Executando a Function
SELECT OBTER_DESCRICAO_SEGMERCADO(2) FROM SEGMERCADO
WHERE ROWNUM = 1;
