-- Funções de Conversões

-- Extract, Extrai um período de um data especifica
SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'DD-MM-YYYY')) FROM DUAL;

-- Conversão para NUMBER
SELECT TO_NUMBER('10') + 10 FROM DUAL;

-- Conversão TOCHAR
SELECT TO_CHAR(1234.293, '9999,99') FROM DUAL;

-- NVL (CONVERTE UM VALOR NULO PARA UM VALOR ESPECIFICADO
SELECT NVL(NULL, 0) FROM DUAL;

SELECT NVL(A.NOME, 'SEM NOME') "VENDEDOR", NVL(A.BAIRRO, 'SEM BAIRRO') "BAIRRO VENDEDOR", 
       NVL(B.NOME, 'SEM NOME') "NOME CLIENTE", NVL(B.BAIRRO, 'SEM BAIRRO') "BAIRRO CLIENTE"
FROM TABELA_DE_VENDEDORES A
FULL JOIN
TABELA_DE_CLIENTES B
ON A.BAIRRO = B.BAIRRO
