-- Desafio Function UTF 03
-- Crie uma função para concaternar o endereço

SELECT * FROM [TABELA DE CLIENTES]

SELECT CONCAT([ENDERECO 1], ' | ', BAIRRO, ' | ', CIDADE, ' | ', ESTADO, ' | ', CEP) 
FROM [TABELA DE CLIENTES]

CREATE FUNCTION EnderecoCompleto
(@ENDERECO VARCHAR(100), 
@BAIRRO VARCHAR(50), 
@CIDADE VARCHAR(50),
@ESTADO VARCHAR(2),
@CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
	DECLARE @ENDERECOCOMPLETO VARCHAR(250);

	SET @ENDERECOCOMPLETO = @ENDERECO + ' | ' + @BAIRRO + ' | ' + @CIDADE + ' | ' 
		+ @ESTADO + ' | ' + @CEP;

	SELECT @ENDERECO = [ENDERECO 1], @BAIRRO = BAIRRO, @CIDADE = CIDADE, @ESTADO = ESTADO, @CEP = CEP
	FROM [TABELA DE CLIENTES];

	RETURN @ENDERECOCOMPLETO;


END;

SELECT CPF, DBO.ENDERECOCOMPLETO([ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP) FROM [TABELA DE CLIENTES]
