-- Função 02

-- Numero aleatorio entre 100 e 500
SELECT ROUND(((500-100 - 1) * RAND() + 100), 0);

-- Colocando a função rand em uma variavel, o SQL SERVER não aceitou
CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
AS
BEGIN
	DECLARE @ALEATORIO INT;
	DECLARE @VALORALEATORIO FLOAT;
	SELECT @VALORALEATORIO = RAND()
	SET @ALEATORIO = ROUND(((@VAL_MAX - @VAL_MIN - 1) * @VALORALEATORIO + @VAL_MIN), 0);

	RETURN @ALEATORIO
END;

-- Criar um visão com o function RAND
CREATE VIEW VW_ALEATORIO
AS
SELECT RAND() 'VALOR_ALEATORIO'


CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
AS
BEGIN
	DECLARE @ALEATORIO INT;
	DECLARE @VALORALEATORIO FLOAT;
	SELECT @VALORALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO
	SET @ALEATORIO = ROUND(((@VAL_MAX - @VAL_MIN - 1) * @VALORALEATORIO + @VAL_MIN), 0);

	RETURN @ALEATORIO
END;

SELECT dbo.NumeroAleatorio(1, 10);
