-- Execução de vários comandos em blocos

SELECT * FROM SEGMERCADO;

DECLARE
    V_ID SEGMERCADO.ID%type;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type;  
BEGIN
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    v_ID := 1;
    v_DESCRICAO := 'Varejista';  
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    v_ID := 2;
    v_DESCRICAO := 'Industrial';  
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    v_ID := 3;
    v_DESCRICAO := 'Atacadista';  
    UPDATE SEGMERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    COMMIT;
END;