-- Condição IF PL/SQL
-- PRECISAMOS CRIAR UMA CONDIÇÃO PARA CATEGORIA:
-- PEQUENO ATÉ 10000
-- MÉDIO ENTRE 10001 E 50000
-- MÉDIO GRANDE ENTRE 50001 E 100000
-- GRANDE MAIS DE 100000

SET SERVEROUTPUT ON;

DECLARE
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%TYPE := 65000;
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    IF 
        v_FATURAMENTO <= 10000 THEN v_CATEGORIA := 'PEQUENO';
    ELSIF
        v_FATURAMENTO BETWEEN 10001 AND 50000 THEN v_CATEGORIA := 'MEDIO';
    ELSIF 
        v_FATURAMENTO BETWEEN 50001 AND 100000 THEN v_CATEGORIA := 'MEDIO GRANDE';
    ELSE 
        v_CATEGORIA := 'GRANDE';
    
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('A Categoria é: ' || v_CATEGORIA);
END;