SELECT SUBSTR(CNPJ, 1, 3) || '/' || SUBSTR(CNPJ, 4, 2) || '-' || SUBSTR(CNPJ, 6) "CNPJ_FORMATADO" FROM CLIENTE;


SELECT '68090', SUBSTR('68090', 1, 2) || '/' || SUBSTR('68090', 3, 4) || '-' || SUBSTR('68090', 5) FROM DUAL;

SELECT * FROM CLIENTE;

CREATE OR REPLACE PROCEDURE FORMATACAO_CNPJ
(    p_CNPJ IN CLIENTE.CNPJ%type, 
    p_CNPJ_SAIDA OUT CLIENTE.CNPJ%type
)
IS
BEGIN
    p_CNPJ_SAIDA := SUBSTR(p_CNPJ,1,3) || '/' || SUBSTR(p_CNPJ,4,2) || '-' || SUBSTR(p_CNPJ,6);
END;



